require('../../bootstrap');
import {renderBlockParameters} from './blockParameters';
import {renderCkeditor} from './ckeditor';
require('./filterTable');
import {renderFingerprint} from './fingerprint';
import {renderForm} from './form';
import {renderGoogleBot} from './googleBot';
import {renderInputCounter} from './inputCounter';
import {renderInputHighlight} from './inputHighlight';
import {renderLocaleSeo} from './localeSeo';
import {renderLocaleTabs} from './localeTabs';
import {renderMenuItems} from './menuItems';
import {renderMessage} from './messages';
require('./modalDeleteImage');
require('./modalImage');
import {renderModalDelete} from './modalDelete';
import {renderModalMenuItem} from './modalMenuItem';
import {renderOnOffSwitch} from './onOffSwitch';
import {renderPagination} from './pagination';
import {renderSelects } from './selects';
import {renderSitemap} from './sitemap';
require('./sortable');
import {renderTable} from './table';
import {renderTabs} from './tabs';
import {renderTopMenu } from './topbarMenu';
require('./uploadImage');
import {renderWait} from './wait';

renderBlockParameters();
renderCkeditor();
renderFingerprint();
renderForm();
renderGoogleBot();
renderInputCounter();
renderInputHighlight();
renderLocaleSeo();
renderLocaleTabs();
renderMenuItems();
renderMessage();
renderModalDelete();
renderModalMenuItem();
renderOnOffSwitch();
renderPagination();
renderSelects();
renderSitemap();
renderTable();
renderTabs();
renderTopMenu();
renderWait();