require('../../bootstrap');
require('./blockParameters');
require('./ckeditor');
require('./filterTable');
require('./fingerprint');
require('./form');
require('./googleBot');
require('./inputCounter');
require('./inputHighlight');
require('./localeSeo');
require('./localeTabs');
require('./localeTags');
require('./menuItems');
require('./messages');
require('./modalDelete');
require('./modalImage');
require('./modalMenuItem');
require('./onOffSwitch');
require('./pagination');
require('./selects');
require('./sitemap');
require('./sortable');
require('./table');
require('./tabs');
require('./topbarMenu');
require('./uploadImage');
require('./wait');


